name: Continous Integration

on:
  workflow_call:
    secrets:
      VERDACCIO_AUTH_TOKEN:
        required: false

    inputs:
      enterprise:
        description: "Flag to use enterprise registry"
        type: boolean
        required: false
        default: false

      node_version:
        description: "Node versions to test"
        type: string
        required: false
        default: "['16', '18']"

env:
  HUSKY: 0

jobs:
  scanning:
    name: GitGuardian scan
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@v1.26.0
        with:
          args: -v
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA:  ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  run-ci:
    name: Run CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ${{ fromJson(inputs.node_version) }}
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 120
    steps:
      - name: Expose github environment as shell variables
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          to_envs() { jq -r "to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""; }
          echo "$SECRETS_CONTEXT" | to_envs >> $GITHUB_ENV
      - name: Checkout code 🛎️
        uses: actions/checkout@v4

      - name: Setup node 🏗️
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: ${{ inputs.enterprise && 'https://registrynpm.storefrontcloud.io' || '' }}

      - name: Get cache 🗄️
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ matrix.node_version }}

      - name: Install dependencies (OS)
        if: ${{ !steps.cache.outputs.cache-hit }}
        shell: bash
        run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VERDACCIO_AUTH_TOKEN }}

      - name: Detect circular dependencies 🔄
        uses: vuestorefront/vue-storefront/actions/circular-dependencies@main
        with:
          filesPath: 'packages/**/*.{ts,vue}'

      - name: Check licenses 🧪
        uses: vuestorefront/vue-storefront/actions/check-licenses@main
        with:
          projectPath: ${{ github.workspace }}

      - name: Build project
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ runner.os }}-${{ github.event.pull_request.head.sha }}
          overwrite: true
          path: |
            coverage
            packages/**/coverage

      - name: Lint project
        run: yarn lint
